language: rust
rust:
  - stable
os:
  - linux
  - osx
  # TODO: Uncomment when we can figure out missing DLL resulting in failed compilations.
  # - windows
cache: cargo

before_script:
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo build --verbose --all
  - cargo test --verbose --all
