trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

# Take templates from the rust-azure-pipelines repository.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#repository-resource
resources:
  repositories:
    - repository: templates
      type: github
      name: xoac/rust-azure-pipelines
      ref: refs/heads/master ## We may also want to change it to refs/tags/TAG_NAME.
      endpoint: PipelinesTemplates

jobs:
# Check formatting
- template: ci/rustfmt.yml@templates
  parameters:
    name: rustfmt
    displayName: Check formatting

# Cargo check
- template: ci/cargo-check.yml@templates
  parameters:
    name: cargo_check
    displayName: Cargo check

################
# Test stage   #
###############

# Test stable
- template: ci/test.yml@templates
  parameters:
    dependsOn:
      - cargo_check
    name: cargo_test_stable
    displayName: Cargo test
    cross: true # Test on Windows and macOS

# Test nightly
- template: ci/test.yml@templates
  parameters:
    name: cargo_test_nightly
    displayName: Cargo test
    rust_version: nightly

# Test cross
# List of supported targets is available here: https://github.com/rust-embedded/cross#supported-targets
- template: ci/cargo-cross.yml@templates
  parameters:
        name: cargo_cross
        displayName: Cross check and test
        rust_version: stable # You can specify here beta, nightly, or a specfic version, e.g. 1.31
        check_targets:
          - i686-unknown-freebsd
          # - thumbv7em-none-eabihf # bare metal require no_std! feature enabled.
        test_targets:
          - mips-unknown-linux-gnu
          - armv7-unknown-linux-musleabihf
          - x86_64-unknown-linux-gnu

