[package]
name = "kosmonaut"
version = "0.1.0"
authors = ["Tyler Wilcock <twilco.o@protonmail.com>"]
edition = "2018"

[dependencies]
app_units = "0.7.1"
cssparser = "0.25.8"
clap = "2.33.0"
gl = { path = "crates/gl" }
glutin = "0.22.0-alpha4"
html5ever = "0.24.0"
matches = "0.1.8"
rand = "0.7.0"
selectors = "0.21.0"
smallbitvec = "2.3.0"
strum = "0.16.0"
strum_macros = "0.16.0"
tempdir = "0.3.7"
derive_builder = "0.8.1"

[features]
gl_debug = ["gl/debug"]
